const express=require('express');
const pool=require('../config/database');
const {validateTelemetry,validatePlan,validateTransition}=require('../domain/energyDispatchPolicy');
const router=express.Router();
const tenantOf=(req)=>String(req.user.tenant_id||req.user.id);

router.post('/telemetry',async(req,res,next)=>{try{const tenant=tenantOf(req),body=req.body||{};const last=await pool.query('SELECT MAX(source_sequence) AS sequence FROM energy_telemetry WHERE tenant_id=$1 AND source=$2 AND site_id=$3',[tenant,body.source_ref,body.home_ref]);const row=validateTelemetry(body,last.rows[0].sequence);await pool.query(`INSERT INTO energy_telemetry(tenant_id,site_id,source,source_sequence,observed_at,values,quality,provenance) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[tenant,row.home_ref,row.source_ref,row.sequence,row.recorded_at,{power_watts:row.power_watts,...row.values},row.quality||'unverified',{device_ref:row.device_ref,schema_version:row.schema_version,checksum:row.checksum,gap:row.gap}]);res.status(202).json({accepted:true,sequence:row.sequence,gap:row.gap});}catch(error){if(error.code==='23505')return res.status(200).json({accepted:true,replayed:true});next(error);}});

router.post('/cases',async(req,res,next)=>{try{if(!req.body.idempotency_key||!req.body.site_id||!req.body.constraints||!req.body.objective)throw new Error('idempotency_key, site_id, constraints, and objective are required');const tenant=tenantOf(req);const result=await pool.query(`INSERT INTO energy_dispatch_cases(tenant_id,site_id,owner_id,idempotency_key,constraints,objective) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(tenant_id,idempotency_key) DO UPDATE SET idempotency_key=EXCLUDED.idempotency_key RETURNING *`,[tenant,req.body.site_id,String(req.user.id),req.body.idempotency_key,req.body.constraints,req.body.objective]);res.status(201).json(result.rows[0]);}catch(error){next(error);}});

router.post('/cases/:id/plan',async(req,res,next)=>{try{const tenant=tenantOf(req),plan=validatePlan(req.body);const result=await pool.query('UPDATE energy_dispatch_cases SET plan=$1,updated_at=NOW() WHERE id=$2 AND tenant_id=$3 RETURNING *',[{...req.body,...plan},req.params.id,tenant]);if(!result.rows[0])return res.status(404).json({error:'Dispatch case not found'});res.json(result.rows[0]);}catch(error){next(error);}});

router.post('/cases/:id/transition',async(req,res,next)=>{const client=await pool.connect();try{const tenant=tenantOf(req);await client.query('BEGIN');const found=await client.query('SELECT * FROM energy_dispatch_cases WHERE id=$1 AND tenant_id=$2 FOR UPDATE',[req.params.id,tenant]);const current=found.rows[0];if(!current){await client.query('ROLLBACK');return res.status(404).json({error:'Dispatch case not found'});}if(Number(req.body.version)!==current.version){await client.query('ROLLBACK');return res.status(409).json({error:'Stale workflow version'});}validateTransition(current.stage,req.body.to_stage,{...req.body.context,role:req.user.role||'home_owner',actorId:String(req.user.id),createdBy:current.owner_id});const result=await client.query('UPDATE energy_dispatch_cases SET stage=$1,version=version+1,updated_at=NOW() WHERE id=$2 RETURNING *',[req.body.to_stage,current.id]);const receipt=req.body.context?.deviceReceipt;if(receipt?.provider&&receipt?.receipt_id)await client.query(`INSERT INTO energy_integration_deliveries(tenant_id,case_id,provider,operation,idempotency_key,status,receipt) VALUES($1,$2,$3,$4,$5,'acknowledged',$6) ON CONFLICT(tenant_id,provider,idempotency_key) DO NOTHING`,[tenant,current.id,receipt.provider,'device_dispatch',receipt.receipt_id,receipt]);await client.query('INSERT INTO energy_workflow_audit(tenant_id,case_id,actor_id,action,from_stage,to_stage,payload) VALUES($1,$2,$3,$4,$5,$6,$7)',[tenant,current.id,String(req.user.id),'energy.transitioned',current.stage,req.body.to_stage,req.body.context||{}]);await client.query('COMMIT');res.json(result.rows[0]);}catch(error){await client.query('ROLLBACK').catch(()=>{});next(error);}finally{client.release();}});
module.exports=router;
